<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddl_tempatLahir</name>
   <tag></tag>
   <elementGuidId>03fbbb8c-6cce-47ed-81ee-6528ad138e34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;dashboardForm-p-0&quot;]/div/div/div/div/div/div[2]/div[7]/div[2]/div/div/div/select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
