<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_noHandphone</name>
   <tag></tag>
   <elementGuidId>ccff5ef1-1b1b-43d3-9ad5-071990395332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;dashboardForm-p-0&quot;]/div/div/div/div/div/div[2]/div[6]/div[2]/div[1]/div/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
